// All pages
export const PAGE_FADE_DURATION = 1.5
export const TRANSITION_LAYER_DURATION = 1

// Homepage
export const HOME_PAGE_COVER_FILL_DURATION = 1.5
export const HOME_PAGE_LEAVE_DURATION = HOME_PAGE_COVER_FILL_DURATION + PAGE_FADE_DURATION
