siteURL="https://amine-bouneggar.com"
linkPrefix=""
siteTitle="Amine Bouneggar | French Interactive & Product Designer"
siteDescription='My name is Amine Bouneggar, I’m a french Art director and Designer based in Paris. Previously at Bold Beyond, Purée Maison, Hello Design and UZIK. Graduated in Master Design from HETIC.'
socialNetworks = [
  { name = "Linkedin", href = "https://www.linkedin.com/in/aminebouneggar" },
  { name = "Behance", href = "https://www.behance.net/thefrenchdesigner" },
  { name = "Mail", href = "mailto:amine.bouneggar7@gmail.com" }
]
