siteTitle="Amine Bouneggar"
siteDescription="I’m Amine, a 21 years old French designer and freelancer based in Paris."
siteURL="http://www.amine-bouneggar.com"
linkedIn="https://linkedin.com/in/aminebouneggar"
behance="https://behance.net"
mail="amine.bouneggar7@gmail.com"
