siteURL="https://amine-bouneggar.com"
linkPrefix=""
siteTitle="Amine Bouneggar | French Interactive & Product Designer"
siteDescription="My name is Amine Bouneggar, I'm a French creative designer based in Paris specializing in interactive and product design. Previously at Bold Beyond, Purée Maison, Hello Design and UZIK. Graduated in Master Design from HETIC."
socialNetworks = [
  { name = "Linkedin", href = "https://www.linkedin.com/in/aminebouneggar" },
  { name = "Mail", href = "mailto:amine.bouneggar7@gmail.com" }
]
